# Generated by Django 2.0.7 on 2018-11-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bintype', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('council', models.CharField(max_length=200)),
            ],
        ),
    ]
