# Generated by Django 2.0.7 on 2018-11-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_binschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binschedule',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
